---
name: Test

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'

jobs:
    lint:
        runs-on: ubuntu-22.04

        steps:
        - name: Checkout code
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2 on 2024-10-03

        - name: Set up Python
          uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0 on 2025-04-23
          with:
              python-version: '3.11'
              cache: 'pip'

        - name: Install dependencies
          run: |
              python3 -m pip install --upgrade pip
              pip install -r requirements.txt

        - name: Run ruff linter
          run: ruff check .

        - name: Run ruff formatter
          run: ruff format --check .

    test:
        runs-on: ubuntu-22.04

        steps:
        - name: Checkout code
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2 on 2024-10-03

        - name: Set up Python
          uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0 on 2025-04-23
          with:
              python-version: '3.13'

        - name: Install dependencies
          run: |
              python3 -m pip install --upgrade pip
              pip install -r requirements.txt

        - name: Run yamllint on detection files
          run: yamllint detections/

        - name: Run pytest
          run: pytest

        - name: Validate Sigma rules
          run: sigma check detections/
